name: Check and Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  PLUGIN_NAME: obsidian-wordpress

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Build
        id: build
        run: |
          npm install
          npm run build
